CREATE TABLE IF NOT EXISTS ducklake_metadata (
    key VARCHAR NOT NULL,
    value VARCHAR NOT NULL,
    scope VARCHAR,
    scope_id BIGINT
);

CREATE TABLE IF NOT EXISTS ducklake_snapshot (
    snapshot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    schema_version BIGINT NOT NULL DEFAULT 0,
    next_catalog_id BIGINT NOT NULL DEFAULT 0,
    next_file_id BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ducklake_schema (
    schema_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schema_name VARCHAR NOT NULL,
    path VARCHAR NOT NULL DEFAULT '',
    path_is_relative BOOLEAN NOT NULL DEFAULT TRUE,
    begin_snapshot BIGINT NOT NULL,
    end_snapshot BIGINT
);

CREATE TABLE IF NOT EXISTS ducklake_table (
    table_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schema_id BIGINT NOT NULL,
    table_name VARCHAR NOT NULL,
    path VARCHAR NOT NULL DEFAULT '',
    path_is_relative BOOLEAN NOT NULL DEFAULT TRUE,
    begin_snapshot BIGINT NOT NULL,
    end_snapshot BIGINT
);

CREATE TABLE IF NOT EXISTS ducklake_column (
    column_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id BIGINT NOT NULL,
    column_name VARCHAR NOT NULL,
    column_type VARCHAR NOT NULL,
    column_order BIGINT NOT NULL,
    nulls_allowed BOOLEAN DEFAULT TRUE,
    parent_column BIGINT,
    begin_snapshot BIGINT NOT NULL,
    end_snapshot BIGINT
);

CREATE TABLE IF NOT EXISTS ducklake_data_file (
    data_file_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id BIGINT NOT NULL,
    begin_snapshot BIGINT NOT NULL,
    end_snapshot BIGINT,
    path VARCHAR NOT NULL,
    path_is_relative BOOLEAN NOT NULL DEFAULT TRUE,
    file_size_bytes BIGINT NOT NULL,
    footer_size BIGINT,
    encryption_key VARCHAR,
    record_count BIGINT,
    row_id_start BIGINT,
    mapping_id BIGINT
);

CREATE TABLE IF NOT EXISTS ducklake_delete_file (
    delete_file_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_file_id BIGINT NOT NULL,
    table_id BIGINT NOT NULL,
    path VARCHAR NOT NULL,
    path_is_relative BOOLEAN NOT NULL DEFAULT TRUE,
    file_size_bytes BIGINT NOT NULL,
    footer_size BIGINT,
    encryption_key VARCHAR,
    delete_count BIGINT,
    begin_snapshot BIGINT NOT NULL,
    end_snapshot BIGINT
);

CREATE TABLE IF NOT EXISTS ducklake_inlined_data_tables (
    table_id BIGINT NOT NULL,
    table_name VARCHAR NOT NULL,
    schema_version BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS ducklake_schema_versions (
    begin_snapshot BIGINT NOT NULL,
    schema_version BIGINT NOT NULL,
    table_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS ducklake_table_stats (
    table_id BIGINT PRIMARY KEY,
    record_count BIGINT NOT NULL DEFAULT 0,
    next_row_id BIGINT NOT NULL DEFAULT 0,
    file_size_bytes BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_schema_name_active
ON ducklake_schema(schema_name) WHERE end_snapshot IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_table_name_active
ON ducklake_table(schema_id, table_name) WHERE end_snapshot IS NULL;

CREATE INDEX IF NOT EXISTS idx_column_active
ON ducklake_column(table_id, begin_snapshot, end_snapshot, column_order);

CREATE INDEX IF NOT EXISTS idx_data_file_active
ON ducklake_data_file(table_id, begin_snapshot, end_snapshot);

CREATE INDEX IF NOT EXISTS idx_inlined_data_tables_table
ON ducklake_inlined_data_tables(table_id, schema_version);

CREATE INDEX IF NOT EXISTS idx_schema_versions_table
ON ducklake_schema_versions(table_id, schema_version, begin_snapshot);

INSERT INTO ducklake_metadata (key, value, scope, scope_id)
SELECT 'data_inlining_row_limit', '10', NULL, NULL
WHERE NOT EXISTS (
    SELECT 1 FROM ducklake_metadata WHERE key = 'data_inlining_row_limit' AND scope IS NULL
);
